### ISSUE TITLE
Support for Ubuntu 22.04?

### ISSUE THREAD

**Issue by jiapei100** [ikwzm/ZynqMP-FPGA-Ubuntu20.04-Ultra96#6]
1. When will you help to provide support for Ubuntu 22.04?
2. Did you ever try : pynq for Ultra96-V2?
3. an one-way converter from **mini DP** to **HDMI** will do? It looks a cheaper **mini DP** to **HDMI** won't have Ultra96-V2 display.

**Comment by ikwzm** [comment]
Thank you for the issue.

> 1. When will you help to provide support for Ubuntu 22.04?

ZynqMP + Ubuntu22.04 is in the following repository.

https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu22.04-Desktop

> 2. Did you ever try : pynq for Ultra96-V2?

No. I'm not using PYNQ.

> 3. an one-way converter from mini DP to HDMI will do? It looks a cheaper mini DP to HDMI won't have Ultra96-V2 display

I use this Mini DP to HDMI. 
For Ultra96, it must be an active converter.
https://www.amazon.co.jp/dp/B00S0BWR2K/

**Comment by jiapei100** [comment]
@ikwzm 
Thank you very much for your prompt reply... Quite clear... Thank you ...
